// --- DO SQLite row schemas ---
export { EntitySchema, type Entity } from "./entity";
export {
  ClaimModeSchema,
  type ClaimMode,
  ClaimSchema,
  type Claim,
} from "./claim";
export {
  JournalEventKindSchema,
  type JournalEventKind,
  JournalEventSchema,
  type JournalEvent,
} from "./journal";
export {
  ArtifactPointerSchema,
  type ArtifactPointer,
  EntityArtifactReferenceSchema,
  type EntityArtifactReference,
  ArtifactRelationshipTypeSchema,
  type ArtifactRelationshipType,
  ArtifactRelationshipSchema,
  type ArtifactRelationship,
  ArtifactSearchResultSchema,
  type ArtifactSearchResult,
  EntitySearchResultSchema,
  type EntitySearchResult,
} from "./artifact";
export { FenceSchema, type Fence } from "./fence";
export { PresenceSchema, type Presence } from "./presence";
export {
  EntityRelationshipTypeSchema,
  type EntityRelationshipType,
  EntityRelationshipSchema,
  type EntityRelationship,
} from "./relationship";

// --- Signal schemas ---
export {
  SignalKindSchema,
  type SignalKind,
  SignalSchema,
  type Signal,
} from "./signal";

// --- DO SQLite: schema history ---
export {
  SchemaHistorySchema,
  type SchemaHistory,
  ApplyStrategySchema,
  type ApplyStrategy,
} from "./schema-history";

// --- D1 global table schemas ---
export {
  D1ProjectSchema,
  type D1Project,
  D1TokenSchema,
  type D1Token,
  D1IdempotencySchema,
  type D1Idempotency,
} from "./d1";

// --- Config schemas ---
export {
  TilaProjectConfigSchema,
  type TilaProjectConfig,
  TilaSchemaTomlSchema,
  type TilaSchemaToml,
  type FieldDeclaration,
  type WorkUnit,
  type ReferenceSlot,
  type ArtifactKind,
  type TemplateDefinition,
  type TemplateEntity,
  type TemplateRelationship,
  RecordDefinitionSchema,
  type RecordDefinition,
} from "./config";
export { TilaInfraConfigSchema, type TilaInfraConfig } from "./infra-config";

// --- API request/response contracts ---
export {
  ErrorEnvelopeSchema,
  type ErrorEnvelope,
  AcquireRequestSchema,
  type AcquireRequest,
  AcquireSuccessResponseSchema,
  type AcquireSuccessResponse,
  RenewRequestSchema,
  type RenewRequest,
  RenewSuccessResponseSchema,
  type RenewSuccessResponse,
  ReleaseRequestSchema,
  type ReleaseRequest,
  ReleaseSuccessResponseSchema,
  type ReleaseSuccessResponse,
  StateResponseSchema,
  type StateResponse,
  CreateEntityRequestSchema,
  type CreateEntityRequest,
  UpdateEntityRequestSchema,
  type UpdateEntityRequest,
  ArchiveRequestSchema,
  type ArchiveRequest,
  EntityResponseSchema,
  type EntityResponse,
  EntityListResponseSchema,
  type EntityListResponse,
  ListReadyEntitiesResponseSchema,
  type ListReadyEntitiesResponse,
  CompactEntitySchema,
  type CompactEntity,
  CompactEntityListResponseSchema,
  type CompactEntityListResponse,
  CompactEntityResponseSchema,
  type CompactEntityResponse,
  PaginatedEntityListResponseSchema,
  type PaginatedEntityListResponse,
  PaginatedCompactEntityListResponseSchema,
  type PaginatedCompactEntityListResponse,
  SummaryResponseSchema,
  type SummaryResponse,
  EntityDetailResponseSchema,
  type EntityDetailResponse,
  ArchiveSuccessResponseSchema,
  type ArchiveSuccessResponse,
  CreateEntityRelationshipRequestSchema,
  type CreateEntityRelationshipRequest,
  CreateEntityRelationshipResponseSchema,
  type CreateEntityRelationshipResponse,
  ListEntityRelationshipsRequestSchema,
  type ListEntityRelationshipsRequest,
  ListEntityRelationshipsResponseSchema,
  type ListEntityRelationshipsResponse,
  DeleteEntityRelationshipRequestSchema,
  type DeleteEntityRelationshipRequest,
  DeleteEntityRelationshipResponseSchema,
  type DeleteEntityRelationshipResponse,
  JournalQuerySchema,
  type JournalQuery,
  JournalResponseSchema,
  type JournalResponse,
  PresenceHeartbeatRequestSchema,
  type PresenceHeartbeatRequest,
  PresenceListResponseSchema,
  type PresenceListResponse,
  PresenceAllListResponseSchema,
  type PresenceAllListResponse,
  PresenceHeartbeatSuccessResponseSchema,
  type PresenceHeartbeatSuccessResponse,
  StateListResponseSchema,
  type StateListResponse,
  HealthResponseSchema,
  type HealthResponse,
  WhoamiResponseSchema,
  type WhoamiResponse,
  DOHealthResponseSchema,
  type DOHealthResponse,
  DoctorProbeResponseSchema,
  type DoctorProbeResponse,
  SqliteColumnInfoSchema,
  type SqliteColumnInfo,
  SchemaMigrationRecordSchema,
  type SchemaMigrationRecord,
  DoctorSchemaSuccessResponseSchema,
  type DoctorSchemaSuccessResponse,
  DoctorSchemaStaleResponseSchema,
  type DoctorSchemaStaleResponse,
  DoctorSchemaResponseSchema,
  type DoctorSchemaResponse,
  TokenIssueRequestSchema,
  type TokenIssueRequest,
  TokenIssueResponseSchema,
  type TokenIssueResponse,
  TokenRevokeResponseSchema,
  type TokenRevokeResponse,
  TokenListItemSchema,
  type TokenListItem,
  TokenListResponseSchema,
  type TokenListResponse,
  AddEntityArtifactReferenceRequestSchema,
  type AddEntityArtifactReferenceRequest,
  EntityArtifactReferenceListResponseSchema,
  type EntityArtifactReferenceListResponse,
  ReconcileDetailSchema,
  type ReconcileDetail,
  ReconcileReportSchema,
  type ReconcileReport,
  SearchRebuildDetailSchema,
  type SearchRebuildDetail,
  SearchRebuildReportSchema,
  type SearchRebuildReport,
  SearchDriftCheckNameSchema,
  type SearchDriftCheckName,
  SearchDriftFindingSchema,
  type SearchDriftFinding,
  SearchDriftReportSchema,
  type SearchDriftReport,
  ArtifactSearchResponseSchema,
  type ArtifactSearchResponse,
  ArtifactSearchQuerySchema,
  type ArtifactSearchQuery,
  ArtifactTextWriteRequestSchema,
  type ArtifactTextWriteRequest,
  ArtifactPutResponseSchema,
  type ArtifactPutResponse,
  ArtifactListResponseSchema,
  type ArtifactListResponse,
  ArtifactRelationshipOkResponseSchema,
  type ArtifactRelationshipOkResponse,
  ArtifactRelationshipListResponseSchema,
  type ArtifactRelationshipListResponse,
  InstantiateTemplateRequestSchema,
  type InstantiateTemplateRequest,
  InstantiateTemplateResponseSchema,
  type InstantiateTemplateResponse,
  RepoRegisterRequestSchema,
  type RepoRegisterRequest,
  RepoRegisterResponseSchema,
  type RepoRegisterResponse,
  RepoDeleteResponseSchema,
  type RepoDeleteResponse,
  RecordCreateRequestSchema,
  type RecordCreateRequest,
  RecordSetRequestSchema,
  type RecordSetRequest,
  RecordPatchRequestSchema,
  type RecordPatchRequest,
  RecordArchiveRequestSchema,
  type RecordArchiveRequest,
  RecordUnarchiveRequestSchema,
  type RecordUnarchiveRequest,
  RecordItemSchema,
  type RecordItem,
  RecordGetResponseSchema,
  type RecordGetResponse,
  RecordMutateResponseSchema,
  type RecordMutateResponse,
  RecordListItemSchema,
  type RecordListItem,
  RecordListResponseSchema,
  type RecordListResponse,
  RecordHistoryItemSchema,
  type RecordHistoryItem,
  RecordHistoryResponseSchema,
  type RecordHistoryResponse,
  RecordTypesResponseSchema,
  type RecordTypesResponse,
  RecordSearchResultSchema,
  type RecordSearchResult,
  UnifiedSearchResultSchema,
  type UnifiedSearchResult,
  UnifiedSearchResponseSchema,
  type UnifiedSearchResponse,
  UnifiedSearchQuerySchema,
  type UnifiedSearchQuery,
  ArtifactGrepLineSchema,
  ArtifactGrepResultSchema,
  ArtifactGrepResponseSchema,
  type ArtifactGrepResponse,
  ArtifactGrepQuerySchema,
  type ArtifactGrepQuery,
} from "./api";

// --- Signal API request/response contracts ---
export {
  SendSignalRequestSchema,
  type SendSignalRequest,
  SendSignalResponseSchema,
  type SendSignalResponse,
  InboxResponseSchema,
  type InboxResponse,
  AckSignalResponseSchema,
  type AckSignalResponse,
} from "./signal";

// --- Search schemas ---
export {
  NormalizedArtifactTextSchema,
  type NormalizedArtifactText,
} from "./search";

// --- Session schemas ---
export {
  SessionPermissionSchema,
  type SessionPermission,
  SessionPayloadSchema,
  type SessionPayload,
  GitHubExchangeRequestSchema,
  type GitHubExchangeRequest,
  GitHubExchangeResponseSchema,
  type GitHubExchangeResponse,
  GitHubAppInstallationConfigSchema,
  type GitHubAppInstallationConfig,
  GitHubAppExchangeRequestSchema,
  type GitHubAppExchangeRequest,
  GitHubAppInfoResponseSchema,
  type GitHubAppInfoResponse,
  OidcExchangeRequestSchema,
  type OidcExchangeRequest,
} from "./session";

// --- Session cookie schemas (UI httpOnly cookie flow) ---
export {
  SessionExchangeRequestSchema,
  type SessionExchangeRequest,
  SessionExchangeResponseSchema,
  type SessionExchangeResponse,
  SessionStatusResponseSchema,
  type SessionStatusResponse,
} from "./session-cookie";

// --- Gate schemas ---
export {
  GateAwaitTypeSchema,
  type GateAwaitType,
  GateStatusSchema,
  type GateStatus,
  GateSchema,
  type Gate,
  CreateGateRequestSchema,
  type CreateGateRequest,
  ResolveGateRequestSchema,
  type ResolveGateRequest,
  GateResponseSchema,
  type GateResponse,
  GateListResponseSchema,
  type GateListResponse,
} from "./gate";

// --- Deploy route constants ---
export { RUN_WORKER_FIRST } from "./deploy-routes";

// --- Record schemas ---
export {
  RecordTypeSchema,
  type RecordType,
  RecordKeySchema,
  type RecordKey,
  RecordTagSchema,
  type RecordTag,
  RecordValueSchema,
  type RecordValue,
  formatRecordResource,
  parseRecordResource,
  canonicalJson,
  canonicalJsonSha256,
} from "./record";
