import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const [name] = process.argv.slice(2);
const symbols = {
  cli: "VERSION",
  sdk: "SDK_VERSION",
  "backend-do": "DO_CODE_VERSION",
};
if (!Object.hasOwn(symbols, name))
  throw new Error("Expected cli, sdk, or backend-do");
const root = new URL("../", import.meta.url);
const pkg = JSON.parse(
  readFileSync(new URL(`packages/${name}/package.json`, root), "utf8"),
);
const revision =
  process.env.TILA_BUILD_REVISION ||
  execFileSync("git", ["rev-parse", "--short", "HEAD"], {
    cwd: fileURLToPath(root),
    encoding: "utf8",
  }).trim();
const value = name === "backend-do" ? revision : pkg.version;
const output = new URL(`packages/${name}/src/version.ts`, root);
const content = `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const ${symbols[name]} = ${JSON.stringify(value)};\n`;
let previous;
try {
  previous = readFileSync(output, "utf8");
} catch (error) {
  if (error.code !== "ENOENT") throw error;
}
if (previous !== content) writeFileSync(output, content);
